### ISSUE TITLE
propagate errors from import task to the user

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab/qgis-gtfs-plugin#4]
Steps to reproduce:

1) load sample_data/broken.zip

Goal:

* show error infobar (and also reason)

Eg.

File 'sample_data/broken.zip': File is not a zip file

shown probably by `finished()`.

Reason taken from exception

```
File "/home/martin/git/ctu-geoforall-lab/qgis-gtfs-plugin/GTFS.py", line 300, in run
              csv_files = self.unzip_file(self.GTFS_folder)
              File "/home/martin/git/ctu-geoforall-lab/qgis-gtfs-plugin/GTFS.py", line 369, in unzip_file
              with ZipFile(GTFS_folder, 'r') as zip:
              File "/usr/lib/python3.9/zipfile.py", line 1257, in __init__
              self._RealGetContents()
              File "/usr/lib/python3.9/zipfile.py", line 1324, in _RealGetContents
              raise BadZipFile("File is not a zip file")
             zipfile.BadZipFile: File is not a zip file
```

**Comment by landam** [comment]
@Kozzba To be done:

1. type xxx
2. press Load 

No error

**Comment by landam** [comment]
On Linux it fails with `IsDirectory`

**Comment by landam** [comment]
```
2021-02-03T16:50:00     WARNING    Traceback (most recent call last):
              File "/home/martin/git/ctu-geoforall-lab/qgis-gtfs-plugin/../qgis-gtfs-plugin/GTFS.py", line 307, in run
              csv_files = self.unzip_file(self.GTFS_folder)
              File "/home/martin/git/ctu-geoforall-lab/qgis-gtfs-plugin/../qgis-gtfs-plugin/GTFS.py", line 382, in unzip_file
              with ZipFile(GTFS_folder, 'r') as zip:
              File "/usr/lib/python3.9/zipfile.py", line 1239, in __init__
              self.fp = io.open(file, filemode)
             IsADirectoryError: [Errno 21] Is a directory: 'x2'
```
